services:
  db:
    image: neo4j:5.26.5
    container_name: neo4j_db
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD}
    ports:
      - "7687:7687"  # Для bolt-соединений 
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "cypher-shell", "--username", "neo4j", "--password", "${NEO4J_PASSWORD}", "RETURN 1"]
      interval: 10s
      timeout: 10s
      retries: 5

  backend:
    build: ./backend
    container_name: fastapi_backend
    environment:
      - NEO4J_URI=bolt://db:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=${NEO4J_PASSWORD} 
    volumes:
      - ./backend/static/images:/static/images 
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_frontend
    environment:
      - REACT_APP_API_URL=http://backend:8000 
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app_network

volumes:
  neo4j_data:
  neo4j_logs:

networks:
  app_network:
    driver: bridge
